import { generateRandomFaceId } from "./generateRandomFaceId.js";
import { elements } from "./elements.js";
import { colors } from "./colors.js";

//sets the dice to a random face
export function setTheDice() {
	let faceId = generateRandomFaceId();

	setFace(faceId);
}

//it sets the color of the dice of that of the currentTurn
export function setDiceColor(currentTurn) {
	elements.dice.style.backgroundColor = colors[currentTurn];
}

//it sets the dice to the random number generated by rollTheDice() function
export function setFace(faceId) {
	elements.faces.forEach((face) => {
		if (face.id === faceId) {
			face.classList.add("turn");
			face.classList.remove("hide");
		} else {
			face.classList.add("hide");
			face.classList.remove("turn");
		}
	});
}
