export let elements = {
	colorHouses: document.querySelectorAll(".color-house"),
	tracks: document.querySelectorAll(".tracks"),
	tracksHorizontal: document.querySelectorAll(".tracks-horizontal"),
	tracksVertical: document.querySelectorAll(".tracks-vertical"),
	tracksHorizontalIndividual: document.querySelectorAll(".track-horizontal"),
	tracksVerticalIndividual: document.querySelectorAll(".track-vertical"),
	tracksIndividual: document.querySelectorAll(".track"),
	redRooms: document.querySelectorAll(".red-room"),
	greenRooms: document.querySelectorAll(".green-room"),
	blueRooms: document.querySelectorAll(".bleu-room"),
	orangeRooms: document.querySelectorAll(".orange-room"),
	brackets: document.querySelectorAll(".bracket"),
	safeBrackets: document.querySelectorAll(".safe-bracket"),
};
