import { elements } from "./elements.js";

let colors = {
	red: "#f23b3b",
	green: "#328b32",
	blue: "#7171bb",
	orange: "#34ea26",
};

let players = {
	red: {
		start: "bracket2",
		finish: "bracket44",
		next: "green",
		homeStart: "bracket45",
		homeEnd: "bracket48",
		nextToFinish: "bracket1",
		home: "bracket61",
	},

	green: {
		start: "bracket13",
		finish: "bracket11",
		next: "orange",
		homeStart: "bracket49",
		homeEnd: "bracket52",
		nextToFinish: "bracket12",
		home: "bracket62",
	},

	orange: {
		start: "bracket24",
		finish: "bracket22",
		next: "blue",
		homeStart: "bracket53",
		homeEnd: "bracket56",
		nextToFinish: "bracket23",
		home: "bracket63",
	},

	blue: {
		start: "bracket35",
		finish: "bracket33",
		next: "red",
		homeStart: "bracket57",
		homeEnd: "bracket60",
		nextToFinish: "bracket34",
		home: "bracket64",
	},
};

let currentTurn;
let currentTurnPlayers;

let faceValue;

let currentBracketId;

let currentGlowingPlayers = [];

//this sets the basic properties of the board
setBoard();

function setBoard() {
	//the game starts from red
	currentTurn = "red";

	setTurn(currentTurn);

	setTheDice();

	//movePlayerToBracketId("blueplayer2", "bracket25");
}

//turn is given to whatever color is in currentTurn
function setTurn(turn) {
	currentTurn = turn;

	elements.turnTags.forEach((tag) => {
		if (tag.classList.contains(`${turn}-turn-tag`)) {
			tag.classList.add("show");
		} else {
			tag.classList.remove("show");
		}
	});

	setDiceColor(currentTurn);
}

//it sets the color of the dice of that of the currentTurn
function setDiceColor(currentTurn) {
	elements.dice.style.backgroundColor = colors[currentTurn];
}

// elements.safeBrackets.forEach((bracket) => {
// 	bracket.innerText = "x";
// });

elements.brackets.forEach((bracket) => {
	if (!bracket.classList.contains("safe-bracket")) {
		bracket.innerText = "";
	}
});

//event listener to listen for clicking of the dice
elements.dice.addEventListener("click", (event) => {
	if (
		event.target.classList.contains("face") ||
		event.target.classList.contains("point")
	) {
		rollTheDice(currentTurn);
	}
});

//sets the dice to a random face
function setTheDice() {
	let faceId = generateRandomFaceId();

	setFace(faceId);
}

//it generates a random faceId for the dice
function generateRandomFaceId() {
	let faceId = `face${Math.ceil(Math.random() * 6)}`;
	return faceId;
}

//rolls the dice to a random face
function rollTheDice(currentTurn) {
	let faceId = generateRandomFaceId();
	currentTurnPlayers = document.querySelectorAll(`.${currentTurn}-player`);

	let currentInHousePlayers = Array.from(currentTurnPlayers).filter(
		(player) => {
			if (player.classList.contains(`${currentTurn}-player`)) {
				return player;
			}
		}
	);

	currentGlowingPlayers = [];

	showAnimation();

	setTimeout(function () {
		setFace(faceId);

		hideAnimation();

		faceValue = document.getElementById(faceId).children.length;

		if (faceValue === 6) {
			currentTurnPlayers.forEach((player) => {
				glow(player);
			});
		} else {
			let currentOutsidePlayers = document.querySelectorAll(
				`.outside-player.${currentTurn}-player`
			);
			if (currentOutsidePlayers.length > 0) {
				Array.from(currentOutsidePlayers).forEach((player) => {
					glow(player);
					if (currentGlowingPlayers.length === 0) {
						setTurn(players[currentTurn].next);
					}
				});
			} else {
				setTurn(players[currentTurn].next);
			}
		}
	}, 900);
}

//it shows the animation of the roll of the dice
function showAnimation() {
	elements.dice.style.animation = ` diceRollAnimation 300ms ease-in 3  `;
}

//it sets the dice to the random number generated by rollTheDice() function
function setFace(faceId) {
	elements.faces.forEach((face) => {
		if (face.id === faceId) {
			face.classList.add("turn");
			face.classList.remove("hide");
		} else {
			face.classList.add("hide");
			face.classList.remove("turn");
		}
	});
}

//it hides the animation of the roll of the dice
function hideAnimation() {
	elements.dice.style.animation = "none";
}

//it makes the currentTurnPlayers glow
function glow(player) {
	let playerBracketId = player.parentNode.id;
	let playerBracketIdNum = getBracketIdNum(playerBracketId);
	let playerHomeBracketIdNum = getBracketIdNum(
		players[players[currentTurn].next].homeStart
	);

	if (playerBracketIdNum + faceValue <= playerHomeBracketIdNum) {
		player.classList.add("glow");
		currentGlowingPlayers.push(player);
	}
}

//event listener for when the user clickes one of the glowing currentTurn players
elements.gameBoard.addEventListener("click", (event) => {
	if (event.target.classList.contains("glow")) {
		stopGlowing(document.querySelectorAll(".player"));

		currentBracketId = event.target.parentNode.id;

		if (event.target.classList.contains("in-house-player")) {
			movePlayerToBracketId(event.target, players[currentTurn].start);
		} else {
			moveForward(event.target, currentBracketId);
		}
	}
});

//it stops the glowing of all currentTurnPlayers
function stopGlowing(players) {
	players.forEach((player) => {
		player.classList.remove("glow");
	});
}

//it moves the clicked player to the bracket of the id
function movePlayerToBracketId(player, nextBracketId) {
	if (player.classList.contains("in-house-player")) {
		player.classList.remove("in-house-player");
		player.classList.add("outside-player");
	}

	let playerClass = String(player.classList);
	let playerId = player.id;

	let bracket = document.getElementById(nextBracketId);

	document.getElementById(playerId).remove();
	//player.remove();

	bracket.innerHTML += ` <div class="${playerClass}" id=${playerId}></div> `;

	currentBracketId = bracket.id;

	checkEachBracket();
}

//it moves the clicked player forward
function moveForward(player) {
	let currentBracketIdNum = getBracketIdNum(currentBracketId);
	let home;

	for (let i = 0; i < faceValue; i++) {
		let nextBracketId;

		nextBracketId = getNextBracketId(currentBracketIdNum + i);

		if (nextBracketId === "bracket45" && currentTurn !== "red") {
			nextBracketId = `bracket${faceValue - i}`;
			movePlayerToBracketId(player, nextBracketId);
			break;
		}

		if (nextBracketId === `${players[currentTurn].nextToFinish}`) {
			let homeStartBracketIdNum = getBracketIdNum(
				players[currentTurn].homeStart
			);
			nextBracketId = `bracket${
				homeStartBracketIdNum + (faceValue - i - 1)
			}`;
			movePlayerToBracketId(player, nextBracketId);
			break;
		}

		if (
			nextBracketId === `${players[players[currentTurn].next].homeStart}`
		) {
			nextBracketId = players[currentTurn].home;
			movePlayerToBracketId(player, nextBracketId);
			home = true;
			document
				.getElementById(`${player.id}`)
				.classList.remove("outside-player");
			break;
		}

		movePlayerToBracketId(player, nextBracketId);
	}

	if (faceValue !== 6 && home !== true) {
		setTurn(players[currentTurn].next);
	}
}

function getNextBracketId(bracketId) {
	return `bracket${bracketId + 1}`;
}

function checkEachBracket() {
	let brackets = document.querySelectorAll(".bracket");

	brackets.forEach((bracket) => {
		if (bracket.children.length > 1) {
			if (bracket.children.length === 2) {
				bracket.children[0].classList.add("shift-left");
				bracket.children[1].classList.add("shift-right");
			} else if (bracket.children.length === 3) {
				bracket.children[0].classList.add("shift-left");
				bracket.children[1].classList.add("shift-right");
				bracket.children[2].classList.add("shift-top");
			} else if (bracket.children.length === 4) {
				bracket.children[0].classList.add("shift-left");
				bracket.children[1].classList.add("shift-right");
				bracket.children[2].classList.add("shift-top");
				bracket.children[3].classList.add("shift-bottom");
			}
		} else {
			Array.from(bracket.children).forEach((child) => {
				child.classList.remove("shift-left");
				child.classList.remove("shift-right");
				child.classList.remove("shift-top");
				child.classList.remove("shift-bottom");
			});
		}
	});
}

function getBracketIdNum(bracketId) {
	let currentBracketIdArr = bracketId.split("");
	let currentBracketIdNumArr = currentBracketIdArr.filter((ele) => {
		if (Number(ele) === Number(ele)) {
			return ele;
		}
	});
	return Number(currentBracketIdNumArr.join(""));
}
